### ISSUE TITLE
Basic example workflow

### ISSUE THREAD

**Issue by crisogray** [logtd/ComfyUI-InstanceDiffusion#14]
Hi, thanks for this port to Comfyui.

I was wondering if there was an example workflow just for generating images grounded with bounding boxes, as I have been unable to get it working so far.

The other examples are all video specific and don't set it up how you would for images alone.

Thanks

**Comment by logtd** [comment]
Hi, thanks for your interest.

Unfortunately there's no nodes that work well with raw image input at this point. It's possible Kijai's spline editor (or his other nodes) can create bounding boxes for single frames that work with this.
