### ISSUE TITLE
Comfy itself requires torch, so it's redundant for this node to require it.

### ISSUE THREAD

**Issue by NeedsMoar** [logtd/ComfyUI-InstanceDiffusion#2]
As per title.  :D

Possibly adds processing overhead to node updates through ComfyUI-Manager as well, since in the case of this node "torch" is the only requirement;  the file could just not exist... (?) @ltdrdata

**Comment by ltdrdata** [comment]
"torch" is a basic requirement for ComfyUI, and it seems appropriate to remove it from the requirement.txt file because different versions of torch need to be installed for each environment.

**Comment by logtd** [comment]
Hi all, thanks for the report.

I'll remove this from requirements.
