### ISSUE TITLE
It doesn't seem to work. I'm not sure what the problem is.

### ISSUE THREAD

**Issue by xunte** [logtd/ComfyUI-InstanceDiffusion#4]
![image](https://github.com/logtd/ComfyUI-InstanceDiffusion/assets/58557441/0317636e-c6fd-465f-bd60-bf0b2368169e)

**Comment by logtd** [comment]
Hello, 
Sorry I won't be able to determine what the issue is from that screenshot. 

You could try using the example workflow and make changes from there. Then you should get a feel for how the nodes work and what may be wrong in this workflow.

**Comment by shadowcz007** [comment]
> ![image](https://private-user-images.githubusercontent.com/58557441/314017362-0317636e-c6fd-465f-bd60-bf0b2368169e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzI2MDIsIm5iZiI6MTcxMTUzMjMwMiwicGF0aCI6Ii81ODU1NzQ0MS8zMTQwMTczNjItMDMxNzYzNmUtYzZmZC00NjVmLWJkNjAtYmYwYjIzNjgxNjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjBjMjcwZDIxZjNiMzBjNmIyMDRjYjQ0ZDQ2ZjA5ZGI5ZmY4MmJlYzIzMzFkMTk0NTk4ODMxNzE5NzZhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oMzvItfodP9cJZEQBS5U6nyfQCnpTGYwR-C5spy4938)

me too

**Comment by logtd** [comment]
Hi, I won't be able to determine what your issue is from the screenshots.

I've just updated InstanceDiffusion and checked that it works with the most recent versions of ComfyUI, Yolo, Supervision, and AnimateDiff-Evolved. 

I'd recommend trying the example workflow with updated versions of nodes/ComfyUI.

Thanks!
